apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: keis2ovlu-go
  janus-idp.io/tekton: keis2ovlu-go
  backstage.io/kubernetes-id: keis2ovlu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: keis2ovlu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
