apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: keis2ovlu-go 
  janus-idp.io/tekton: keis2ovlu-go
  backstage.io/kubernetes-id: keis2ovlu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: keis2ovlu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  